Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "definitions.pyc", line 1, in <module>
  File "libtcodpy.pyc", line 60, in <module>
  File "ctypes\__init__.pyc", line 440, in __getitem__
  File "ctypes\__init__.pyc", line 435, in __getattr__
  File "ctypes\__init__.pyc", line 365, in __init__
WindowsError: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "definitions.pyc", line 1, in <module>
  File "libtcodpy.pyc", line 60, in <module>
  File "ctypes\__init__.pyc", line 440, in __getitem__
  File "ctypes\__init__.pyc", line 435, in __getattr__
  File "ctypes\__init__.pyc", line 365, in __init__
WindowsError: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "definitions.pyc", line 1, in <module>
  File "libtcodpy.pyc", line 60, in <module>
  File "ctypes\__init__.pyc", line 440, in __getitem__
  File "ctypes\__init__.pyc", line 435, in __getattr__
  File "ctypes\__init__.pyc", line 365, in __init__
WindowsError: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "definitions.pyc", line 1, in <module>
  File "libtcodpy.pyc", line 60, in <module>
  File "ctypes\__init__.pyc", line 440, in __getitem__
  File "ctypes\__init__.pyc", line 435, in __getattr__
  File "ctypes\__init__.pyc", line 365, in __init__
WindowsError: [Error 126] The specified module could not be found
